DATASET_NAMES = {
    "city_temperature_f": "City-Temp",
    "stocks_uk": "Stocks-UK",
    "stocks_usa_c": "Stocks-USA",
    "stocks_de": "Stocks-DE",
    "neon_bio_temp_c": "IR-bio-temp",
    "neon_wind_dir": "Wind-dir",
    "neon_pm10_dust": "PM10-dust",
    "neon_dew_point_temp": "Dew-Point-Temp",
    "neon_air_pressure": "Air-Pressure",
    "basel_wind_f": "Basel-wind",
    "basel_temp_f": "Basel-temp",
    "bitcoin_f": "Bitcoin-price",
    "bitcoin_f_f": "Bitcoin-price",
    "bird_migration_f": "Bird-migration",
    "air_sensor_f": "Air-sensor",
    "food_prices": "Food-prices",
    "poi_lat": "POI-lat",
    "poi_lon": "POI-lon",
    "bitcoin_transactions_f": "Blockchain-tr",
    "ssd_hdd_benchmarks_f": "SD-bench",
    "gov10": "Gov/10",
    "gov26": "Gov/26",
    "gov30": "Gov/30",
    "gov31": "Gov/31",
    "gov40": "Gov/40",
    "medicare1": "Medicare/1",
    "medicare9": "Medicare/9",
    "nyc29": "NYC/29",
    "cms1": "CMS/1",
    "cms9": "CMS/9",
    "cms25": "CMS/25",
    "arade4": "Arade/4"
}

