"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan alp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum alp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan alp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum alp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan alp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum alp"

"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan pde"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum pde"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan pde"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum pde"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan pde"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum pde"

"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan patas"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum patas"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan patas"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum patas"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan patas"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum patas"

"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan gorilla"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum gorilla"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan gorilla"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum gorilla"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan gorilla"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum gorilla"

"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan alp_rd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum alp_rd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan alp_rd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum alp_rd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan alp_rd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum alp_rd"

"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan ztsd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum ztsd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan ztsd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum ztsd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan ztsd"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum ztsd"

"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan chimp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum chimp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan chimp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum chimp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan chimp"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum chimp"

"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan chimp128"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum chimp128"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan chimp128"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum chimp128"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan chimp128"
"$TARGET_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum chimp128"

