#!/bin/bash
# Use $CLONED_DIR in your script
echo "CLONED_DIR is $CLONED_DIR"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan alp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum alp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan alp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum alp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan alp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum alp"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan pde"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum pde"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan pde"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum pde"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan pde"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum pde"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan patas"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum patas"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan patas"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum patas"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan patas"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum patas"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan gorilla"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum gorilla"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan gorilla"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum gorilla"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan gorilla"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum gorilla"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan alp_rd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum alp_rd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan alp_rd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum alp_rd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan alp_rd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum alp_rd"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan ztsd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum ztsd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan ztsd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum ztsd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan ztsd"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum ztsd"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan chimp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum chimp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan chimp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum chimp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan chimp"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum chimp"

"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 scan chimp128"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 1 sum chimp128"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 scan chimp128"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 8 sum chimp128"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 scan chimp128"
"$CLONED_DIR/build/publication/source_code/bench_end_to_end/run_query 16 sum chimp128"
